services:
  storage:
    shared: false
    class: Vainyl\Core\Storage\Storage
  storage.proxy:
    abstract: true
    class: Vainyl\Core\Storage\Proxy\AbstractStorageProxy
    arguments: ['@storage']
  storage.assert:
    decorates: storage
    class: Vainyl\Core\Storage\Decorator\AssertStorageDecorator
    arguments: ['@storage.assert.inner']
  storage.duplicate:
    decorates: storage
    class: Vainyl\Core\Storage\Decorator\DuplicateStorageDecorator
    arguments: ['@storage.duplicate.inner']
  bootstrapper.composite:
    class: Vainyl\Core\Application\Composite\CompositeBootstrapper
  comparator.factory:
    class: Vainyl\Core\Comparator\Factory\ComparatorFactory
  comparator.factory.logger:
    decorates: comparator.factory
    class: Vainyl\Core\Comparator\Factory\Decorator\LoggerComparatorFactoryDecorator
    arguments: ['@comparator.factory.inner', '@logger']
  comparator.storage:
    parent: storage.proxy
    class: Vainyl\Core\Comparator\Storage\ComparatorStorage
    arguments: ['comparator.factory']
  renderer.factory:
    class: Vainyl\Core\ArrayX\Factory\RendererFactory
  renderer.factory.logger:
    decorates: renderer.factory
    class: Vainyl\Core\ArrayX\Factory\Decorator\LoggerRendererFactoryDecorator
    arguments: ['@renderer.factory.inner', '@logger']
  renderer.storage:
    parent: storage.proxy
    class: Vainyl\Core\ArrayX\Storage\RendererStorage
    arguments: ['@renderer.factory']