services:
  counter:
    shared: false
    class: Vainyl\Core\Counter
  ds.map:
    shared: false
    class: Ds\Map
  storage.prototype:
    shared: false
    class: Vainyl\Core\Storage\Proxy\AbstractStorageProxy
    arguments: ['@ds.map']
  storage.prototype.assert:
    decorates: storage.prototype
    class: Vainyl\Core\Storage\Decorator\AssertStorageDecorator
    arguments: ['@storage.prototype.assert.inner']
  storage.prototype.duplicate:
    decorates: storage.proxy
    class: Vainyl\Core\Storage\Decorator\DuplicateStorageDecorator
    arguments: ['@storage.prototype.duplicate.inner']
  bootstrapper.composite:
    class: Vainyl\Core\Application\Composite\CompositeBootstrapper
    arguments: ['@storage.prototype']
  comparator.factory:
    class: Vainyl\Core\Comparator\Factory\ComparatorFactory
  comparator.factory.logger:
    decorates: comparator.factory
    class: Vainyl\Core\Comparator\Factory\Decorator\LoggerComparatorFactoryDecorator
    arguments: ['@comparator.factory.logger.inner', '@logger']
  comparator.storage:
    class: Vainyl\Core\Comparator\Storage\ComparatorStorage
    arguments: ['comparator.factory']
  renderer.factory:
    class: Vainyl\Core\ArrayX\Factory\RendererFactory
  renderer.factory.logger:
    decorates: renderer.factory
    class: Vainyl\Core\ArrayX\Factory\Decorator\LoggerRendererFactoryDecorator
    arguments: ['@renderer.factory.logger.inner', '@logger']
  renderer.storage:
    class: Vainyl\Core\ArrayX\Storage\RendererStorage
    arguments: ['@storage.prototype', '@renderer.factory']
  bootstrapper.shutdown:
    class: Vainyl\Core\Application\ShutdownFunctionBootstrapper
    arguments: ['@logger']
    tags:
      - {name: bootstrapper}