services:
  app.di:
    synthetic: true
  app.environment:
    synthetic: true
  logger.app:
    synthetic: true
    tags:
      - {name: 'logger', channel: 'app'}
  counter:
    shared: false
    class: Vainyl\Core\Counter
  ds.map:
    shared: false
    class: Ds\Map
  ds.set:
    shared: false
    class: Ds\Set
  storage.set.prototype:
    shared: false
    class: Vainyl\Core\Storage\Adapter\StorageSetAdapter
    arguments: ['@ds.set']
  storage.prototype:
    shared: false
    class: Vainyl\Core\Storage\Proxy\StorageProxy
    arguments: ['@ds.map']
  storage.prototype.assert:
    shared: false
    decorates: storage.prototype
    class: Vainyl\Core\Storage\Decorator\AssertStorageDecorator
    arguments: ['@storage.prototype.assert.inner']
  storage.prototype.duplicate:
    shared: false
    decorates: storage.prototype
    class: Vainyl\Core\Storage\Decorator\DuplicateStorageDecorator
    arguments: ['@storage.prototype.duplicate.inner']
  bootstrapper.composite:
    class: Vainyl\Core\Application\Composite\CompositeBootstrapper
    arguments: ['@storage.prototype']
  bootstrapper: '@bootstrapper.composite'
  comparator.factory:
    class: Vainyl\Core\Comparator\Factory\ComparatorFactory
  comparator.factory.logger:
    decorates: comparator.factory
    class: Vainyl\Core\Comparator\Factory\Decorator\LoggerComparatorFactoryDecorator
    arguments: ['@comparator.factory.logger.inner', '@logger.app']
  comparator.storage:
    class: Vainyl\Core\Comparator\Storage\ComparatorStorage
    arguments: ['@storage.prototype', '@comparator.factory']
  renderer.factory:
    class: Vainyl\Core\ArrayX\Factory\RendererFactory
  renderer.factory.logger:
    decorates: renderer.factory
    class: Vainyl\Core\ArrayX\Factory\Decorator\LoggerRendererFactoryDecorator
    arguments: ['@renderer.factory.logger.inner', '@logger.app']
  renderer.storage:
    class: Vainyl\Core\ArrayX\Storage\RendererStorage
    arguments: ['@storage.prototype', '@renderer.factory']
  bootstrapper.shutdown:
    class: Vainyl\Core\Application\ShutdownFunctionBootstrapper
    arguments: ['@logger.app']
    tags:
      - {name: bootstrapper}
  encoder.storage:
    class: Vainyl\Core\Encoder\Storage\EncoderStorage
    arguments: ['@storage.prototype']
  decoder.storage:
    class: Vainyl\Core\Encoder\Storage\DecoderStorage
    arguments: ['@storage.prototype']
  extension.storage:
    class: Vainyl\Core\Extension\ExtensionStorage
    arguments: ['@storage.prototype']
  encoder.null:
    class: Vainyl\Core\Encoder\NullEncoder
    tags:
      - {name: encoder, alias: 'null'}
      - {name: encoder, alias: 'text/html'}
  decoder.null:
    class: Vainyl\Core\Encoder\NullEncoder
    tags:
      - {name: decoder, alias: 'null'}
      - {name: decoder, alias: 'text/html'}
  encoder.json:
    class: Vainyl\Core\Encoder\JsonEncoder
    tags:
      - {name: encoder, alias: 'json'}
      - {name: encoder, alias: 'application/json'}
  decoder.json:
    class: Vainyl\Core\Encoder\JsonEncoder
    tags:
      - {name: decoder, alias: 'json'}
      - {name: decoder, alias: 'application/json'}
  hydrator.registry:
    class: Vainyl\Core\Hydrator\Registry\HydratorRegistry
    arguments: ['@storage.prototype', '@app.di']
